services:
  sdk:
    image: openwrt/sdk:x86_64-v22.03.4
    volumes:
      - .:/feed
      - ./bin:/builder/bin
      - ./build.sh:/builder/build.sh
      - ./key-build:/builder/key-build
    command: /builder/build.sh
      