name: Openwrt Luci Build Bot
on:
  push:
    branches: main
    paths:
      - '.github/workflows/build-luci-release.yml'
      - 'patch.sh'
      - 'packages/**'
      - '!packages/**/github/workflows/**'
      - '!packages/**/README*'
      - '!packages/**/.gitignore'
      - '!packages/**/LICENSE'
      - '!packages/**/LICENSES'

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-21.02.7
          - x86_64-22.03.5
          - x86_64-23.05.2
          - x86_64-SNAPSHOT

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          ./patch.sh ${{ matrix.arch }}
          PACKAGES=$(ls packages | sed 's/\///g' | tr '\n' ' ')
          echo "PACKAGES=${PACKAGES}" >> $GITHUB_ENV

      - name: Build
        # uses: openwrt/gh-action-sdk@main
        uses: ekkog/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          IGNORE_ERRORS: 1
          EXTRA_FEEDS: |
            src-git|ekko_packages|https://github.com/EkkoG/openwrt-packages.git
          PACKAGES: ${{ env.PACKAGES }}

      - name: List files
        run: |
          ls -R bin/
          
      - name: Upload feed
        uses: Pendect/action-rsyncer@8e05ffa5c93e5d9c9b167796b26044d2c616b2b9
        with:
          flags: '-ahvHP'
          options: '--delete'
          src: 'bin/packages/*/action/'
          dest: "${{ secrets.SF_USER }}@frs.sourceforge.net:/home/frs/project/ekko-openwrt-dist/luci/"
        env:
          DEPLOY_KEY: ${{ secrets.SF_KEY }}
          ARCH: ${{ matrix.arch }}


