name: Openwrt Luci Build Bot for 22.03
on:
  push:
    branches: main
    paths:
      - '.github/workflows/build-luci-release-22.03.yml'
      - 'patch.sh'
      - '**'
      - '!config.json'
      - '!**/README*'
      - '!**/.gitignore'
      - '!**/LICENSE'
      - '!**/LICENSES'

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-v22.03.4


    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Prepare feeds
        run: |
          ./patch.sh ${{ matrix.arch }}

      - name: Build
        uses: ekkog/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          IGNORE_ERRORS: 1
          NO_SHFMT_CHECK: 1
          V: 99
          EXTRA_FEEDS: |
            src-git|ekko_packages|https://github.com/EkkoG/openwrt-packages.git
          PACKAGES: |
            luci-app-natmap
            luci-app-mosdns
            luci-theme-argon
            luci-app-openclash
            luci-app-temp-status

      - name: List files
        run: |
          ls -R bin/

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          ARCH=$(echo $ARCH | sed 's/-v/-/g')
          VERSION=$(echo $ARCH | cut -d'-' -f2 | cut -d'.' -f1-2)
          BRANCH="luci/$VERSION"
          cd bin/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.DIST_PUSH_TOKEN }}@github.com/EkkoG/openwrt-dist" HEAD:$BRANCH
